### ISSUE TITLE
error "Couldn't complete the payment validation process" on initial setup

### ISSUE THREAD

**Issue by schenkelchen** [2Checkout/woocommerce#20]
Hi @craigchristenson ,

I'm just in progress with setting up the ["2PayJS/API"](https://github.com/2Checkout/woocommerce/tree/master/twocheckout) version.

I did install the addon successfully, entered Seller ID and Secret Key and also added the IPN URL in cpanel while my 2checkout account is in demo mode.
Now I'm trying to make a test payment by using the [visa card test credentials](https://knowledgecenter.2checkout.com/Documentation/09Test_ordering_system/01Test_payment_methods).
Now I'm running continuously into the following error message, displayed on the checkout page:
![2checkout-woocommerce-api](https://user-images.githubusercontent.com/54481142/114235464-87509180-9980-11eb-8d79-c1eaf222f341.PNG)
`Payment error: Couldn't complete the payment validation process: Error processing the credit card transaction. Please contact the issuer bank for more details, or enter another card.`

I'm not sure if it has to do anything with the module or if it's an issue related to any wrong configuration from my side.
I tried to have a closer look at the issue but so far I'm unable to get any clue. I neither find any information on failed api call attempts in 2checkout's cpanel nor am I able to find the logged data when having checked "Enable logging" in the addon's settings.

It would be great if you can give me a hint on my issue itself and also about how to find the logged debugging data of the addon. If there's any log of api calls in cpanel which I haven't found so far, I'd like to know about it as well.

Best, schenkelchen

**Comment by craigchristenson** [comment]
Are you using John Doe as the name as indicated in the test credentials
article?

**Comment by schenkelchen** [comment]
No, I don't use Jon Doe as card holder's name because there's no field to enter card holder's name in "2PayJS/API" version of the addon.
In the meantime I also installed "Inline Checkout" and "Hosted/Convert-Plus Checkout". I'm not successful with any of them. When choosing the Inline version and clicking in pay button there's no reaction at all on the button click. The Hosted/Convert-Plus version causes an immediate redirection to woocommerce's "my account" page without any page/popup showing up where I can enter card credentials.

**Comment by schenkelchen** [comment]
In my apache logfiles I found an information why the "**Inline Checkout**" might be failing:
`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Two_Checkout_Inline_Helper::is_customer_ip_valid() in /home/webserver_provider.com/app_directory/public_html/wp-content/plugins/twocheckout-inline/wc-twocheckout-inline.php:369\nStack trace:\n#0 /home/webserver_provider.com/app_directory/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(971): WC_Gateway_Twocheckout_Inline->process_payment()\n#1 /home/webserver_provider.com/app_directory/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1183): WC_Checkout->process_order_payment()\n#2 /home/webserver_provider.com/app_directory/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(465): WC_Checkout->process_checkout()\n#3 /home/webserver_provider.com/app_directory/public_html/wp-includes/class-wp-hook.php(292): WC_AJAX::checkout()\n#4 /home/webserver_provider.com/app_directory/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()\n#5 /home/webserver_provider....', referer: https://my_custom_domain.com/shop/my-checkout`

Unfortunately I didn't find such information for the "**Hosted/Convert-Plus Checkout**". So the reason why this checkout fails might be a different one.

**Comment by craigchristenson** [comment]
Thanks you for reporting the inline issue. I was able to replicate it and have push a new release to fix it.

As for the API name issue, you only need to input the name in the Woocommerce checkout form, not the 2PayJS form.

I was unable to recreate the convert plus issue you reported. Could woocommerce be redirecting to my account because some field is required before checkout?

**Comment by schenkelchen** [comment]
Thanks for solving the issue with **Inline Checkout** so fastly, @craigchristenson. It works on my demo account now!

But I've made three small findings which I'd like to let you know about:

1. after confirming credit card credentials (so in the moment when the payment request goes out to twocheckout) a browser popup window opens next to the dynamic popup with card credentials.
![inline_popup](https://user-images.githubusercontent.com/54481142/114602477-f129ad80-9c96-11eb-8a2f-f0d7125bb804.PNG)
I fear that on some browsers this might cause trouble, if they block browser popup consequently. I'm using Opera and it works for the moment but I know Firefox can be very strict about browser popup windows.

2. When I return via the website's menu from order confirmation (https://domain.com/shop/my-checkout/order-received/9999?key=wc_order_12321rmY9r123) to homepage (https://domain.com/) an error is displayed even though payment was successful.
![inline_homepage](https://user-images.githubusercontent.com/54481142/114603017-875dd380-9c97-11eb-98c9-459782b96ed2.PNG)
Also when trying to make another test order immediately thereafter I run into the same error message presented on checkout page. I need to refresh (F5) the page several times before I can place another test order.

3. Furthermore every new order is directly set to status _completed_ instead of _processing_ in my WooCommerce shop. I've found out that this happens due to the fact that twocheckout sends this information immediately after payment via IPN because if I deactivate _Completed orders_ as a trigger to be sent, this doesn't happen anymore.
![inline_order-completed](https://user-images.githubusercontent.com/54481142/114603430-fe936780-9c97-11eb-9fe1-75af8d061924.PNG)
Maybe it's in demo twocheckout only. But as I'm not sure about it, I just let you know.

**Comment by schenkelchen** [comment]
Can you please clarify what I should do to provide you further details on the **Hosted/Convert-Plus Checkout** issue, @craigchristenson.
`I was unable to recreate the convert plus issue you reported. Could woocommerce be redirecting to my account because some field is required before checkout?`
I don't get the point what _redirection to your account_ means.

**Comment by schenkelchen** [comment]
I've done further trials with the **Hosted/Convert-Plus Checkout** addon (Version 1.2.2)

Out of 5 trials when I clicked the purchase button checkout page I got redirected two times to 2checkout.com and found the information there that my cart is empty (which is wrong).
![convert-plus_redirection](https://user-images.githubusercontent.com/54481142/114860207-fe0be580-9deb-11eb-924c-a4247c85dd74.PNG)

Additionally I found the logs in `/public_html/wp-content/uploads/wc-logs` on my webserver which I'm going to share here:
`04-15-2021 @ 19:32:24 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-convert-plus/src/Twocheckout/Helpers/class-convert-plus-helper.php at line 112`
`04-15-2021 @ 19:32:49 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-convert-plus/src/Twocheckout/Helpers/class-convert-plus-helper.php at line 112`
`04-15-2021 @ 19:33:14 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-convert-plus/src/Twocheckout/Helpers/class-convert-plus-helper.php at line 112`
`04-15-2021 @ 19:56:19 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-convert-plus/src/Twocheckout/Helpers/class-convert-plus-helper.php at line 112`
`04-15-2021 @ 19:56:33 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-convert-plus/src/Twocheckout/Helpers/class-convert-plus-helper.php at line 112`
Times in UTC+9
It's always the same error, no matter if I got redirected or not. Anyway I hope the error message gives you a useful hint for debugging.

**Comment by schenkelchen** [comment]
One point to add on the issue with **Inline Checkout**
It's still able to place test orders and still the error message appears after transaction as reported by me on April 13, 18:40 UTC

> 2. When I return via the website's menu from order confirmation (https://domain.com/shop/my-checkout/order-received/9999?key=wc_order_12321rmY9r123) to homepage (https://domain.com/) an error is displayed even though payment was successful.
>    ![inline_homepage](https://user-images.githubusercontent.com/54481142/114603017-875dd380-9c97-11eb-98c9-459782b96ed2.PNG)
>    Also when trying to make another test order immediately thereafter I run into the same error message presented on checkout page. I need to refresh (F5) the page several times before I can place another test order.

I accessed the respective logs for inline an the found the following:
`04-15-2021 @ 20:22:54 - Unable to get proper response from signature generation API. In file /home/domain.com/xxxxx/public_html/wp-content/plugins/twocheckout-inline/src/Twocheckout/Helpers/class-two-checkout-inline-helper.php at line 51`
Time in UTC+9
The error which occurs seems to have similarities with the error which occurs on _Hosted/Convert-Plus Checkout_.

**Comment by schenkelchen** [comment]
Unfortunately the **2PayJS/API** addon doesn't generate a log like the other two addons on my installation, so I can't determine if that one might have the same trouble, too.

**Comment by schenkelchen** [comment]
> Are you using John Doe as the name as indicated in the test credentials article?
For the **2PayJS/API** Addon in might be neccessary that while test mode enabled in Addon settings a card holder name can be chosen to allow transaction to be performed with positive or negative result - depending on the name - and to avoid the error message
`Payment error: Couldn't complete the payment validation process: Error processing the credit card transaction. Please contact the issuer bank for more details, or enter another card.`
as described in my very first post on April 9, 8:22 pm UTC.

**Comment by Mineslu** [comment]
Hello there,
I have already managed to install and activate "Convert-Plus Checkout" and "inline Checkout". But I have the same problem to integrate "2PayJS / API".
In Woocomerce's name field put this:
<img width="1336" alt="Captura de Pantalla 2021-08-23 a la(s) 08 29 58" src="https://user-images.githubusercontent.com/9434043/130455828-32c09f97-5bcd-4230-ba15-a762c1dfe049.png">

And in the form of the cards this:
<img width="1224" alt="Captura de Pantalla 2021-08-23 a la(s) 08 31 11" src="https://user-images.githubusercontent.com/9434043/130455976-ae45af3b-2a49-4ea0-8a5c-8047c39fa7b3.png">


But I get this problem:
Payment error:The provided currency [USD] is not supported with this card type. Supported currencies: []


Greetings
